security:
  password_hashers:
    App\Entity\User:
      algorithm: 'auto'

  providers:
    doctrine:
      entity:
        class: App\Entity\User
        property: username

  enable_authenticator_manager: true

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      pattern: ^/
      form_login:
        login_path: login
        check_path: login_check
        always_use_default_target_path: true
        default_target_path: /

  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/users, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: ROLE_USER }
